/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package onlycs.chess;

import onlycs.chess.types.Board;

public class Main {
	public static void main(String[] args) {
		Board board = Board.create().unwrap();

		board.display();
	}
}
